package practice;
import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class IncompleteBST
{
	public String missingValues(String[] tree)
	{

		return null;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		IncompleteBST obj;
		String answer;
		obj = new IncompleteBST();
		long startTime = System.currentTimeMillis();
		answer = obj.missingValues(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		String[] p0;
		String p1;

		// ----- test 0 -----
//		p0 = new String[]{"? 3", "K 1", "K 2", "K 4", "K 8", "K 16", "K 32", "K 64", "K 128"};
//		p1 = "LMNOPQRSTUVWXYZ";
//		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
//		// ------------------
//
////		// ----- test 1 -----
//		p0 = new String[]{"B 1","? 2"};
//		p1 = "AB";
//		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
////		// ------------------
////
////		// ----- test 2 -----
//		p0 = new String[]{"V 1","? 3"};
//		p1 = "WXYZ";
//		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
//		// ------------------
//
//		// ----- test 3 -----
		p0 = new String[]{"K 1","K 2","A 6","? 12","Y 3"};
		p1 = "";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
//		// ------------------
//
//		// ----- test 4 -----
		p0 = new String[]{"Z 1","Y 2","X 4","W 8","V 16","U 32","T 64","S 128","R 256","Q 512","P 1024","O 2048","N 4096","M 8192","L 16384","K 32768","J 65536","? 131072"};
		p1 = "ABCDEFGHIJ";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
